"""20220712_1600

Revision ID: 6c9a6ac9fa41
Revises: a1ce17a62e94
Create Date: 2022-07-12 16:00:04.980559

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6c9a6ac9fa41'
down_revision = 'a1ce17a62e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
                    sa.Column('createdate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updatedate', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('deletedate', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('itemid', sa.Integer(), nullable=False),
                    sa.Column('itemname', sa.String(length=50), nullable=False),
                    sa.Column('itemdescription', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('itemid')
                    )
    op.create_index(op.f('ix_items_itemname'), 'items', ['itemname'], unique=True)
    op.create_table('baskets',
                    sa.Column('createdate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updatedate', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('deletedate', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('basketid', sa.Integer(), nullable=False),
                    sa.Column('basketclosed', sa.Boolean(), nullable=False),
                    sa.Column('userid', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
                    sa.PrimaryKeyConstraint('basketid')
                    )
    op.create_table('basketitems',
                    sa.Column('createdate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updatedate', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('deletedate', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('itemid', sa.Integer(), nullable=False),
                    sa.Column('basketid', sa.Integer(), nullable=False),
                    sa.Column('itemquantity', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['basketid'], ['baskets.basketid'], ),
                    sa.ForeignKeyConstraint(['itemid'], ['items.itemid'], ),
                    sa.PrimaryKeyConstraint('itemid', 'basketid')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basketitems')
    op.drop_table('baskets')
    op.drop_index(op.f('ix_items_itemname'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
