"""20220712_1513

Revision ID: a1ce17a62e94
Revises: e1c76c2e70ed
Create Date: 2022-07-12 15:13:08.149188

"""
from alembic import op
import sqlalchemy as sa
from  sqlalchemy import Table, MetaData
from sqlalchemy.orm.session import Session
from app.models.user_role import UserRole


# revision identifiers, used by Alembic.
revision = 'a1ce17a62e94'
down_revision = 'e1c76c2e70ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('userroles_userid_fkey', 'userroles', type_='foreignkey')
    op.drop_constraint('userroles_roleid_fkey', 'userroles', type_='foreignkey')
    op.drop_constraint('userroles_pkey', 'userroles', type_='primary')

    # reverse column content
    connection = op.get_bind()

    connection.execute(
        """
            UPDATE userroles SET userid = roleid, roleid = userid
        """
    )
    # end reverse column

    op.create_primary_key(None, 'userroles', ['roleid', 'userid'])
    op.create_foreign_key(None, 'userroles', 'users', ['userid'], ['userid'])
    op.create_foreign_key(None, 'userroles', 'roles', ['roleid'], ['roleid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userroles', type_='foreignkey')
    op.drop_constraint(None, 'userroles', type_='foreignkey')
    op.create_foreign_key('userroles_roleid_fkey', 'userroles', 'users', ['roleid'], ['userid'])
    op.create_foreign_key('userroles_userid_fkey', 'userroles', 'roles', ['userid'], ['roleid'])
    # ### end Alembic commands ###
