"""20221307_1020

Revision ID: bf1119035f7b
Revises: 0e2085bdf1c3
Create Date: 2022-07-13 10:23:10.101662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1119035f7b'
down_revision = '0e2085bdf1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baskets',
    sa.Column('createdate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletedate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('basketid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('basketid')
    )
    op.create_table('items',
    sa.Column('createdate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletedate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('itemid', sa.Integer(), nullable=False),
    sa.Column('itemname', sa.String(length=50), nullable=False),
    sa.Column('itemprice', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('itemid'),
    sa.UniqueConstraint('itemname')
    )
    op.create_table('basket_item',
    sa.Column('createdate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletedate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('basketid', sa.Integer(), nullable=False),
    sa.Column('itemid', sa.Integer(), nullable=False),
    sa.Column('itemquantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basketid'], ['baskets.basketid'], ),
    sa.ForeignKeyConstraint(['itemid'], ['items.itemid'], ),
    sa.PrimaryKeyConstraint('basketid', 'itemid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket_item')
    op.drop_table('items')
    op.drop_table('baskets')
    # ### end Alembic commands ###
