"""20220712_1144

Revision ID: e1c76c2e70ed
Revises: 9e173e9e2486
Create Date: 2022-07-12 11:44:15.550614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Table, MetaData


# revision identifiers, used by Alembic.
revision = 'e1c76c2e70ed'
down_revision = '9e173e9e2486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('createdate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletedate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('roleid', sa.Integer(), nullable=False),
    sa.Column('rolename', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('roleid')
    )
    op.create_index(op.f('ix_roles_rolename'), 'roles', ['rolename'], unique=True)
    op.create_table('userroles',
    sa.Column('createdate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletedate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('roleid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roleid'], ['users.userid'], ),
    sa.ForeignKeyConstraint(['userid'], ['roles.roleid'], ),
    sa.PrimaryKeyConstraint('roleid', 'userid')
    )

    # ### end Alembic commands ###

    # region MIGRATION SCRIPT

    meta = MetaData(bind=op.get_bind())

    meta.reflect(only=('roles',))

    roles_table = Table('roles', meta)

    op.bulk_insert(
        roles_table,
        [
            { "rolename": "USER", "active": True },
            { "rolename": "MODERATOR", "active": True },
            { "rolename": "ADMIN", "active": True },
        ]
    )

    # endregion


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userroles')
    op.drop_index(op.f('ix_roles_rolename'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
